import { deepStrictEqual, strictEqual } from "node:assert/strict"
import { mkdtempSync, readdirSync, rmSync, writeFileSync, utimesSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { describe, it } from "node:test"
import { deltaReports, extractFindings, loadSnapshot, parseFindingLine, pruneSnapshots, renderDeltaFooter, saveSnapshot, shouldSaveSnapshot, snapshotDir, type AuditSnapshot } from "./state.js"

const REPORT = [
  "# Audit Report",
  "",
  "- target: /Users/dev/project",
  "- time: 2026-09-18T10:00:00Z",
  "- playbook: css",
  "",
  "> generated by opencode audit",
  "",
  "## probe (unused-css)",
  "",
  "  - Unused class `.legacy-card` found in styles/main.css",
  "  - Unused variable   --old-accent   defined in tokens.css",
  "  1. Orphaned selector `.footer-nav` in layout.css",
  "",
  "  > a quoted note that should be ignored",
  "  ### sub heading that should be ignored",
  "  -   Collapsed   whitespace   finding   here  ",
  "",
  "## probe (css-size)",
  "",
  "  - Duplicated rule block in components.css",
  "  2. Dead import of reset.css in index.css",
].join("\n")

describe("extractFindings", () => {
  it("collects two-space-indented bullets under probe sections", () => {
    const findings = extractFindings(REPORT)
    deepStrictEqual(findings, [
      "Unused class `.legacy-card` found in styles/main.css",
      "Unused variable --old-accent defined in tokens.css",
      "Orphaned selector `.footer-nav` in layout.css",
      "Collapsed whitespace finding here",
      "Duplicated rule block in components.css",
      "Dead import of reset.css in index.css",
    ])
  })

  it("ignores metadata bullets, headers and blockquotes before the first section", () => {
    const findings = extractFindings(REPORT)
    strictEqual(findings.some((f) => f.startsWith("target:")), false)
    strictEqual(findings.some((f) => f.startsWith("time:")), false)
    strictEqual(findings.some((f) => f.startsWith("playbook:")), false)
    strictEqual(findings.some((f) => f.includes("quoted note")), false)
    strictEqual(findings.some((f) => f.includes("sub heading")), false)
  })

  it("handles numbered bullets", () => {
    const findings = extractFindings("## probe (a)\n\n1. First numbered finding\n\n2. Second numbered finding")
    deepStrictEqual(findings, ["First numbered finding", "Second numbered finding"])
  })

  it("collapses internal whitespace", () => {
    const findings = extractFindings("## probe (a)\n\n- spaced\t\tout   text")
    deepStrictEqual(findings, ["spaced out text"])
  })

  it("ignores everything before the first '## ' heading", () => {
    const findings = extractFindings("- stray bullet before sections\n## probe (a)\n- real finding after heading")
    deepStrictEqual(findings, ["real finding after heading"])
  })

  it("returns [] when there are no sections or bullets", () => {
    deepStrictEqual(extractFindings("# just a header\n\nplain text"), [])
    deepStrictEqual(extractFindings(""), [])
  })

  it("skips deeper-indent evidence bullets under findings", () => {
    const report = [
      "## probe (a)",
      "",
      "  - [high] src/app/page.tsx:12 — missing canonical link",
      "    - evidence: grep 'rel=\"canonical\"' src/app/page.tsx → 0 matches",
      "  - [med] route:/checkout — sitemap entry missing",
    ].join("\n")
    deepStrictEqual(extractFindings(report), [
      "[high] src/app/page.tsx:12 — missing canonical link",
      "[med] route:/checkout — sitemap entry missing",
    ])
  })

  it("skips same-indent evidence:-prefixed bullets", () => {
    const report = [
      "## probe (a)",
      "",
      "- [high] src/app/page.tsx:12 — missing canonical link",
      "- evidence: grep 'rel=\"canonical\"' src/app/page.tsx → 0 matches",
      "- [med] route:/checkout — sitemap entry missing",
    ].join("\n")
    deepStrictEqual(extractFindings(report), [
      "[high] src/app/page.tsx:12 — missing canonical link",
      "[med] route:/checkout — sitemap entry missing",
    ])
  })

  it("skips Note:-prefixed bullets", () => {
    const report = [
      "## probe (a)",
      "",
      "- [med] route:/checkout — sitemap entry missing",
      "- Note: could not verify pagination",
    ].join("\n")
    deepStrictEqual(extractFindings(report), ["[med] route:/checkout — sitemap entry missing"])
  })

  it("collects findings across sections with different native indents", () => {
    const report = [
      "## probe (a)",
      "",
      "- finding at zero indent",
      "## probe (b)",
      "",
      "  - finding at two space indent",
    ].join("\n")
    deepStrictEqual(extractFindings(report), ["finding at zero indent", "finding at two space indent"])
  })
})

describe("parseFindingLine locations", () => {
  it("recognizes bare filenames and Windows drive paths as structured locations", () => {
    const makefile = parseFindingLine("[med] Makefile — missing target")
    strictEqual(makefile?.structured, true)
    strictEqual(makefile?.location, "Makefile")

    const windows = parseFindingLine("[high] C:\\src\\app.tsx:12 — missing check")
    strictEqual(windows?.structured, true)
    strictEqual(windows?.location, "C:\\src\\app.tsx:12")
  })

  it("does not interpret traversal paths as structured locations", () => {
    const parsed = parseFindingLine("[low] ../outside.ts:2 — unsafe path")
    strictEqual(parsed?.structured, false)
  })
})

describe("deltaReports", () => {
  const baseline: AuditSnapshot = {
    playbook: "css",
    target: "/tmp/project",
    time: "2026-09-17T10:00:00Z",
    findings: ["kept finding one", "resolved finding two", "kept finding one"],
  }

  it("returns all current findings as new with resolvedCount 0 on first run", () => {
    const report = "## probe (a)\n\n- finding alpha\n- finding beta"
    const d = deltaReports(null, report)
    deepStrictEqual(d, { newFindings: ["finding alpha", "finding beta"], resolvedCount: 0, total: 2 })
  })

  it("reports only findings not present in the previous snapshot", () => {
    const report = "## probe (a)\n\n- kept finding one\n- brand new finding"
    const d = deltaReports(baseline, report)
    deepStrictEqual(d.newFindings, ["brand new finding"])
    strictEqual(d.resolvedCount, 1)
    strictEqual(d.total, 2)
  })

  it("dedupes repeated bullets within one report", () => {
    const report = "## probe (a)\n\n- repeated finding here\n- repeated finding here\n- other finding here"
    const d = deltaReports(null, report)
    deepStrictEqual(d.newFindings, ["repeated finding here", "other finding here"])
    strictEqual(d.total, 2)
  })

  it("counts every previous finding entry that is gone, including duplicates", () => {
    const d = deltaReports(baseline, "## probe (a)\n\n- unrelated new finding")
    strictEqual(d.resolvedCount, 3)
  })

  it("matches previous findings by exact string identity", () => {
    const report = "## probe (a)\n\n- kept finding one "
    const d = deltaReports(baseline, report)
    deepStrictEqual(d.newFindings, [])
    strictEqual(d.resolvedCount, 1)
    strictEqual(d.total, 1)
  })

  it("does not count a finding as new when only its line number drifts", () => {
    const base: AuditSnapshot = {
      playbook: "css",
      target: "/tmp/project",
      time: "2026-09-17T10:00:00Z",
      findings: ["[high] src/app/page.tsx:12 — missing canonical link"],
    }
    const report = "## probe (a)\n\n- [med] src/app/page.tsx:99 — missing canonical link"
    const d = deltaReports(base, report)
    deepStrictEqual(d.newFindings, [])
    strictEqual(d.resolvedCount, 0)
    strictEqual(d.total, 1)
  })

  it("counts a materially different issue at the same location as new", () => {
    const base: AuditSnapshot = {
      playbook: "css",
      target: "/tmp/project",
      time: "2026-09-17T10:00:00Z",
      findings: ["[high] src/app/page.tsx:12 — missing canonical link"],
    }
    const report = "## probe (a)\n\n- [high] src/app/page.tsx:12 — duplicate h1 on page"
    const d = deltaReports(base, report)
    deepStrictEqual(d.newFindings, ["[high] src/app/page.tsx:12 — duplicate h1 on page"])
    strictEqual(d.resolvedCount, 1)
  })

  it("matches route-keyed findings without a line number", () => {
    const base: AuditSnapshot = {
      playbook: "seo",
      target: "/tmp/project",
      time: "2026-09-17T10:00:00Z",
      findings: ["[med] route:/checkout — sitemap entry missing"],
    }
    const report = "## probe (a)\n\n- [low] route:/checkout — sitemap entry missing"
    const d = deltaReports(base, report)
    deepStrictEqual(d.newFindings, [])
    strictEqual(d.resolvedCount, 0)
  })

  it("matches findings whose path is wrapped in backticks", () => {
    const base: AuditSnapshot = {
      playbook: "css",
      target: "/tmp/project",
      time: "2026-09-17T10:00:00Z",
      findings: ["[high] src/styles/main.css:42 — unused selector .legacy-card"],
    }
    const report = "## probe (a)\n\n- [high] `src/styles/main.css`:42 — unused selector .legacy-card"
    const d = deltaReports(base, report)
    deepStrictEqual(d.newFindings, [])
    strictEqual(d.resolvedCount, 0)
  })
})

describe("renderDeltaFooter", () => {
  const d = { newFindings: ["a", "b"], resolvedCount: 3, total: 7 }

  it("renders the first-run text when there is no baseline", () => {
    strictEqual(renderDeltaFooter(d, null), "> first run — no baseline yet")
  })

  it("renders the delta text with counts and previous time", () => {
    strictEqual(
      renderDeltaFooter(d, "2026-09-17T10:00:00Z"),
      "> 🆕 2 new · 3 resolved · 7 total findings since last run (2026-09-17T10:00:00Z)",
    )
  })
})

describe("shouldSaveSnapshot", () => {
  it("requires at least one successful result and no failures", () => {
    strictEqual(shouldSaveSnapshot([{ error: undefined }, { error: undefined }]), true)
    strictEqual(shouldSaveSnapshot([{ error: undefined }, { error: "probe failed" }]), false)
    strictEqual(shouldSaveSnapshot([{ error: undefined, malformed: true }]), false)
    strictEqual(shouldSaveSnapshot([{ error: undefined, malformed: false }]), true)
    strictEqual(shouldSaveSnapshot([]), false)
  })
})

describe("pruneSnapshots", () => {
  it("keeps the newest JSON snapshots and ignores other files", () => {
    const directory = mkdtempSync(join(tmpdir(), "opencode-audit-snapshots-"))
    try {
      const old = join(directory, "old.json")
      const middle = join(directory, "middle.json")
      const newest = join(directory, "newest.json")
      const temporary = join(directory, ".writing.tmp")
      for (const file of [old, middle, newest, temporary]) writeFileSync(file, "{}")
      const base = new Date("2026-01-01T00:00:00Z")
      utimesSync(old, base, base)
      utimesSync(middle, new Date(base.getTime() + 1000), new Date(base.getTime() + 1000))
      utimesSync(newest, new Date(base.getTime() + 2000), new Date(base.getTime() + 2000))

      pruneSnapshots(directory, 2)
      deepStrictEqual(readdirSync(directory).sort(), [".writing.tmp", "middle.json", "newest.json"])
    } finally {
      rmSync(directory, { recursive: true, force: true })
    }
  })
})

describe("saveSnapshot", () => {
  it("writes a readable snapshot through an atomic temp-file rename", () => {
    const directory = mkdtempSync(join(tmpdir(), "opencode-audit-home-"))
    const previousHome = process.env.HOME
    try {
      process.env.HOME = directory
      const target = "/project/example?token=supersecretvalue"
      const snapshot: AuditSnapshot = {
        playbook: "seo",
        target,
        time: "2026-09-24T00:00:00.000Z",
        findings: ["[high] src/page.tsx:1 — missing canonical"],
      }
      saveSnapshot(snapshot)
      deepStrictEqual(loadSnapshot("seo", target), { ...snapshot, target: "/project/example?token=[REDACTED]" })
      strictEqual(snapshotDir(target).includes("supersecretvalue"), false)
      deepStrictEqual(readdirSync(snapshotDir(target)), ["seo.json"])
    } finally {
      if (previousHome === undefined) delete process.env.HOME
      else process.env.HOME = previousHome
      rmSync(directory, { recursive: true, force: true })
    }
  })
})
